import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "./assets/vite.svg";
import heroImg from "./assets/hero.png";
import "./App.css";
import CompFirst from "./CompFirst.jsx";
import CompSecond from "./CompSecond.jsx";
import CompThird from "./CompThird.jsx";
import CompFourth from "./CompFourth.jsx";
import CompFifth from "./CompFifth.jsx";
import CompSixth from "./CompSixth.jsx";
